// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJ_R9t8BIQqUD_kV97Zqy2yYFKNFCAbo',
    appId: '1:746826983815:web:4cd8084f44249fc2a28b22',
    messagingSenderId: '746826983815',
    projectId: 'my-blood-donor-project',
    authDomain: 'my-blood-donor-project.firebaseapp.com',
    storageBucket: 'my-blood-donor-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLWQKajBOuS4vvFSegFfUNBhlUa26MqI',
    appId: '1:746826983815:android:34f0225ba33d86b9a28b22',
    messagingSenderId: '746826983815',
    projectId: 'my-blood-donor-project',
    storageBucket: 'my-blood-donor-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBN8hP2ZsOf5UYRiu-dFzPADWEnf-Dr6s',
    appId: '1:746826983815:ios:97df0402158175ffa28b22',
    messagingSenderId: '746826983815',
    projectId: 'my-blood-donor-project',
    storageBucket: 'my-blood-donor-project.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBN8hP2ZsOf5UYRiu-dFzPADWEnf-Dr6s',
    appId: '1:746826983815:ios:97df0402158175ffa28b22',
    messagingSenderId: '746826983815',
    projectId: 'my-blood-donor-project',
    storageBucket: 'my-blood-donor-project.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEJ_R9t8BIQqUD_kV97Zqy2yYFKNFCAbo',
    appId: '1:746826983815:web:80d112232f04e3eea28b22',
    messagingSenderId: '746826983815',
    projectId: 'my-blood-donor-project',
    authDomain: 'my-blood-donor-project.firebaseapp.com',
    storageBucket: 'my-blood-donor-project.firebasestorage.app',
  );
}
